MANIFEST: manifest.tsv
REF:
  GRCh38: /net/eichler/vol28/eee_shared/assemblies/hg38/no_alt/hg38.no_alt.fa
  CHM13_v2.0: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/T2T-CHM13v2.fasta
  CHM13_v2.0_noY: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/T2T-CHM13v2_noY.fasta
  GRCh38_noY: /net/eichler/vol28/eee_shared/assemblies/hg38/no_alt/hg38.no_alt-noY.fa
  CHM13v2.masked_Y: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/T2T-CHM13v2.masked_Y.fasta
  CHM13v2.masked_Ypars: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/T2T-CHM13v2.masked_Ypars.fasta
TRF:
  GRCh38: /net/eichler/vol28/software/pipelines/pbsv/anno/hg38_trf_regions.bed
  CHM13_v2.0: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/anno/chm13_t2t_trf.bed
  CHM13_v2.0_noY: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/anno/chm13_t2t_trf.bed
  GRCh38_noY: /net/eichler/vol28/software/pipelines/pbsv/anno/hg38_trf_regions.bed
  CHM13v2.masked_Y: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/anno/chm13_t2t_trf.bed
  CHM13v2.masked_Ypars: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/anno/chm13_t2t_trf.bed
