#!/usr/bin/env bash
# Usage: ./runsnake 80

#!/usr/bin/env bash

# Get directory where the script is located
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

JOB_COUNT=$1

shift

DRMAA_ARGS=" -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -pe serial {threads} -w n -S /bin/bash"

# Load the module where snakemake is installed
module load snakemake/9.3.0

# Make log directory
mkdir -p log

# Run
snakemake \
    --jobname "{rulename}.{jobid}" \
    --executor drmaa \
    --drmaa-args "${DRMAA_ARGS}" \
    -s ${SOURCE_DIR}/Snakefile \
    --use-singularity \
    --singularity-args '--bind /net/:/net/' \
    --printshellcmds \
    --restart-times 3 \
    --latency-wait 15 \
    -j "${JOB_COUNT}" \
    "$@"
