# input vcf with variants to be genotyped
vcf: /path/to/variants.vcf

# reference genome
reference: /path/to/reference.fa

# path to reads (FASTA/FASTQ format, uncompressed)
# for each sample that shall be genotyped
reads:
 sample1: /path/to/reads-sample1.fa
 sample2: /path/to/reads-sample2.fa

# path to PanGenie exectuable
pangenie_genotype: /path/to/PanGenie
pangenie_index: /path/to/PanGenie-index


# name of the output directory
outdir: results
