#!/usr/bin/env bash
# Usage: ./runsnake 30

JOB_COUNT=$1

shift

SNAKEFILE=Snakefile

SUBMIT_TIME=$(printf '%(%Y-%m-%d_%H.%M.%S)T\n' -1)

DRMAA_ARGS=" -V -cwd -j y -o ./log/${SUBMIT_TIME}/ -e ./log/${SUBMIT_TIME}/ -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -l cpuid_level=27 -l disk_free=100G -pe serial {threads} -w n -S /bin/bash"
DRMAA_ARGS=" -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -pe serial {threads} -w n -S /bin/bash"

# Load the module where snakemake is installed
module load miniconda/4.12.0

# Make log directory
mkdir -p log

# Run
snakemake \
    --jobname "{rulename}.{jobid}" \
    --drmaa "${DRMAA_ARGS}" \
    -s ${SNAKEFILE} \
    --use-singularity \
    --singularity-args '--bind /net/:/net/ -C ' \
    --restart-times 3 \
    --printshellcmds \
    --latency-wait 15 \
    -j "${JOB_COUNT}" \
    "$@"
