---
title: "autism"
output: html_document
date: "2024-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- fread("C:/home/autism/r_edits/temp.txt") %>% as.data.frame()

# for each row in the FORMAT column, get a list of which index corresponds to each field
my_FORMAT <- df$FORMAT %>% str_split(":")
index_GT <- lapply(my_FORMAT, function(x){which(x=="GT")}) %>% unlist
index_AD <- lapply(my_FORMAT, function(x){which(x=="AD")}) %>% unlist
index_DP <- lapply(my_FORMAT, function(x){which(x=="DP")}) %>% unlist


# get a vector of indexes for columns corresponding to fa, mo, p1, p2, etc
which_columns_to_split <- which(colnames(df) %in% c("FA", "MO") | grepl("\\.p[0-9]$", colnames(df)))
family_columns_to_cbind <- lapply(which_columns_to_split, function(COL_INDEX){
  split_member <- df[, COL_INDEX] %>% str_split(":")
  # identify which columns have more FORMAT fields than the FA column has fields, we won't be able to get good AD or DP infor for these
  bool_useable <- (my_FORMAT %>% lapply(length) %>% unlist)==(split_member %>% lapply(length) %>% unlist)
  columns_member <- lapply(seq_down(df), function(x){
    if(bool_useable[x]==FALSE){
      if(split_member[[x]][1] %>% grepl("\\/|\\|")){ # check to see if the first field contains GT information
        return(c(split_member[[x]][1], 0,0))
      } else {
        return(c("./.", 0, 0))
      }
    }
    
    # return the corresponding row from current family member, and the corresponding column for each corresponding field
    return(c(split_member[[x]][index_GT[x]],
             split_member[[x]][index_AD[x]],
             split_member[[x]][index_DP[x]]))
  }) %>% do.call(rbind, .) %>% as.data.frame()
  colnames(columns_member) <- paste0(colnames(df)[COL_INDEX], "_", c("GT", "AD", "DP"))
  return(columns_member)
}) %>% do.call(cbind, .) %>% as.data.frame()



```

# asm qc manifest
```{r}
df00 <- read_sheet("https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=0", sheet = "Individual_Stats")
df0 <- fread("C:/home/autism/asm_qc/manifest_job_done1.tab") %>% as.data.frame()
df0[is.na(df0)] <- "NA"


bool_child <- grepl("_(p.|s.)$", df0$sample)
df1 <- data.frame(SAMPLE = df0$sample, 
                  H1 = paste0(
                    "/net/eichler/vol28/projects/autism_genome_assembly/nobackups/asm_ys/", 
                    df0$sample, 
                    "/assemblies/hifiasm/",
                    ifelse(bool_child, "trio/", ""),
                    "0.16.1/",
                    df0$sample, 
                    ".hifiasm.",
                    ifelse(bool_child, "dip", "bp"),
                    ".hap1.p_ctg.gfa.fasta"),
                  H2 = paste0(
                    "/net/eichler/vol28/projects/autism_genome_assembly/nobackups/asm_ys/", 
                    df0$sample, 
                    "/assemblies/hifiasm/",
                    ifelse(bool_child, "trio/", ""),
                    "0.16.1/",
                    df0$sample, 
                    ".hifiasm.",
                    ifelse(bool_child, "dip", "bp"),
                    ".hap2.p_ctg.gfa.fasta"),
                  ILLUMINA = df0$sample,
                  FOFN = paste0(
                    "/net/eichler/vol28/projects/autism_genome_assembly/nobackups/fofn/Illumina/",
                    df0$sample, 
                    "-Illumina.fastq.fofn"),
                  TRIO = lapply(df0$sample, function(x){
                    if(df00$Family_Type[grep(x, df00$SP_ID)] == "Quad, Simplex"){
                      return("NO")
                    } else {
                      return("YES")
                    }}) %>% unlist,
                  MO_ID = ifelse(bool_child, 
                                  df0$sample %>% str_replace("_(p.|s.)$", "_mo"),
                                  "NA"),
                  FA_ID = ifelse(bool_child, 
                                  df0$sample %>% str_replace("_(p.|s.)$", "_fa"),
                                  "NA")
                  
                  )
write.table(df1, "C:/home/autism/asm_qc/manifest.tab.asm_qc.docker.new", sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)

```

```{r}
df00 <- read_sheet("https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=448025372", sheet = "FOFN_summary") %>% as.data.frame()
```
# update tracking sheet
```{r}
df00 <- read_sheet("https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=0", sheet="Individual_Stats") %>% as.data.frame()

man_aqc <- fread("C:/docs/autism/asm_qc/manifest.tab.2024-04-22.finished") %>% as.data.frame()
df00$`asm_QC -- Isaac`[df00$SP_ID %in% man_aqc$SAMPLE] <- "Done"

man_pbsv <- fread("C:/docs/autism/manifest.tab.pbsv.2024-04-23.finished") %>% as.data.frame()
df00$`PBSV -- Isaac`[df00$SP_ID %in% man_pbsv$SAMPLE] <- "Done"

man_aln <- fread("C:/docs/autism/aln.samples") %>% as.data.frame()
df00$`aln -- Isaac`[df00$SP_ID %in% man_aln$sample] <- "Done"
df00$`aln_QC -- Isaac (VBI)`[df00$SP_ID %in% man_aln$sample] <- "Done"

write_sheet(df00, "https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=0", "temp_isaac")
```

```{r}
df1 <- fread("C:/docs/autism/asm_qc/merq.stats.qv.tsv") %>% as.data.frame()
df1 <- df1[!grepl("Both", df1$V1), ]
sample_ids <- df1$V1 %>% str_remove("_hap(1|2)") %>% u
df10 <- lapply(sample_ids, function(x){
  temp_rows <- df1[grepl(x, df1$V1), ]
  data.frame(sample = x, 
             QV_Merqury_hap1 = ifelse(any(grepl("hap1", temp_rows[,1])), temp_rows[grepl("hap1", temp_rows[,1]), 4] %>% round, "NA"), 
             QV_Merqury_hap2 = ifelse(any(grepl("hap2", temp_rows[,1])), temp_rows[grepl("hap2", temp_rows[,1]), 4] %>% round, "NA") 
             ) %>% return()
}) %>% do.call(rbind, . )
rm(df1)

df2 <- fread("C:/docs/autism/asm_qc/merq.stats.completeness.tsv") %>% as.data.frame()
df2 <- df2[!grepl("both", df2$V1), ]
sample_ids <- df2$V1 %>% str_remove("_hap(1|2)") %>% u
df20 <- lapply(sample_ids, function(x){
  temp_rows <- df2[grepl(x, df2$V1), ]
  data.frame(sample = x, 
             Completeness_hap1=ifelse(any(grepl("hap1", temp_rows[,1])), temp_rows[grepl("hap1", temp_rows[,1]), 5] %>% round, "NA"), 
             Completeness_hap2=ifelse(any(grepl("hap2", temp_rows[,1])), temp_rows[grepl("hap2", temp_rows[,1]), 5] %>% round, "NA") 
             ) %>% return()
}) %>% do.call(rbind, . )
rm(df2)

df3 <- fread("C:/docs/autism/asm_qc/contig_stats.tsv") %>% as.data.frame()
sample_ids <- df3$source %>% str_remove("_hap..n50.stats") %>% u
df30 <- lapply(sample_ids, function(x){
  temp_rows <- df3[grep(x, df3$source), ]
  data.frame(sample = x,
             Contig_N50_Mbp_hap1=
               ifelse(any(grepl("hap1", temp_rows[,1])), 
                      temp_rows[grepl("hap1", temp_rows[,1]) & grepl("N50 ", temp_rows[,2]), 2] %>% str_remove("N50 \\(Mbp\\):") %>% str_trim(), 
                      "NA"),
             Contig_N50_Mbp_hap2=
               ifelse(any(grepl("hap2", temp_rows[,1])), 
                      temp_rows[grepl("hap2", temp_rows[,1]) & grepl("N50 ", temp_rows[,2]), 2] %>% str_remove("N50 \\(Mbp\\):") %>% str_trim(), 
                      "NA")
             )
}) %>% do.call(rbind, .)
rm(df3)

df00 <- read_sheet("https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=0", sheet="Individual_Stats") %>% as.data.frame()


df123 <- merge(df10, df20, all = TRUE) %>% merge(df30, all=TRUE)
df123[is.na(df123)] <- "NA"

df01 <- merge(df00, df123, by.x = "SP_ID", by.y="sample", all=TRUE)
df01 <- df01[match(df00$SP_ID, df01$SP_ID), ]
write_sheet(df01, "https://docs.google.com/spreadsheets/d/1NYBlpsY9rizPnUMT_qE1oHg8ZGnYocCaMk7CXciZqyk/edit#gid=0", "temp_isaac")



bool_merq_resubmit <- df123$QV_Merqury_hap1=="NA" | df123$QV_Merqury_hap2=="NA"
bool_contig_resubmit <- df123$Contig_N50_Mbp_hap1 == "NA" | df123$Contig_N50_Mbp_hap2 == "NA"

```



```{r}
BOOLS <- c(TRUE, FALSE)
temp_n <- 15
temp_df <- data.frame(temp1 = sample(BOOLS, temp_n, replace = TRUE),
                      temp2 = sample(BOOLS, temp_n, replace = TRUE),
                      temp3 = sample(BOOLS, temp_n, replace = TRUE),
                      temp4 = sample(BOOLS, temp_n, replace = TRUE))
temp_df$ALL <- lapply(seq_down(temp_df), function(x){
  all(temp_df[x, ])
}) %>% unlist
```



```{r}
df0 <- read.table("C:/docs/autism/manifest.tab", sep="\t", header = TRUE)

df1 <- data.frame(SAMPLE = df0$SAMPLE, 
                  ROLE = ifelse(
                    df0$SAMPLE %>% grepl("_fa$", .), "father", ifelse(
                    df0$SAMPLE %>% grepl("_mo$", .), "mother", ifelse(
                    df0$SAMPLE %>% grepl("_p.$", .), "proband", "sibling"))),
                  FAMILY = df0$SAMPLE %>% gsub("_..$", "", .),
                  HAP1 = paste0("/net/eichler/vol28/projects/autism_genome_assembly/nobackups/assembly_qc/QC_results/saffire/results/",
                                df0$SAMPLE, "_hap1/alignments/", df0$SAMPLE, "_hap1.minimap2.paf"),
                  HAP2 = paste0("/net/eichler/vol28/projects/autism_genome_assembly/nobackups/assembly_qc/QC_results/saffire/results/",
                                df0$SAMPLE, "_hap2/alignments/", df0$SAMPLE, "_hap2.minimap2.paf"))
write.table(df1, "C:/docs/autism/manifest.concatchr.tab", sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)

```






```{r}
df0 <- fread("C:/docs/autism/fofn/sample_list_fofn_to_Isaac.txt") %>% as.data.frame()

my_samples <- u(df0$SAMPLE)

lapply(my_samples, function(x){
  
  write.table(df0$FASTQ[df0$SAMPLE == x], paste0("C:/docs/autism/fofn/", x, ".fofn"), sep="\t", col.names = FALSE, row.names = FALSE, quote=FALSE)
  
  
})


```



```{r}
df0 <- fread("C:/docs/autism/ncdu_autism_sorted.tsv") %>% as.data.frame()
df0$notes <- NULL

file_types <- c(".gfa", ".bin", ".bed", ".yak")
my_regex <- paste0("assemblies/hifiasm/0.16.1/.*","(", paste0(file_types, collapse = "|"), ")$"  )
my_regex2 <- paste0("/asm_ys/.*_(s|p)1/.*.hifiasm.bp.hap")

df1 <- df0[grepl("^/net/eichler/vol28/projects/autism_genome_assembly/nobackups/asm_ys", df0$file), ]
df11 <- df1[grepl(my_regex, df1$file) | grepl(my_regex2, df1$file), ]
write.table(df11$file, "C:/docs/autism/to_delete.txt", sep="\t", col.names = FALSE, row.names = FALSE, quote=FALSE)
```

```{r}
df1 <- readLines("C:/docs/autism/asm_files.txt") %>% as.data.frame()

file_types <- c(".gfa", ".bin", ".bed", ".yak")
my_regex <- paste0("assemblies/hifiasm/0.16.1/.*","(", paste0(file_types, collapse = "|"), ")$"  )
my_regex2 <- paste0("/asm_ys/.*_(s|p)1/.*.hifiasm.bp.hap")

df11 <- df1[grepl(my_regex, df1$.) | grepl(my_regex2, df1$.), ]
write.table(df11, "C:/docs/autism/to_delete.txt", sep="\t", col.names = FALSE, row.names = FALSE, quote=FALSE)
```

```{r}
formals(write.table)$row.names <- FALSE
formals(write.table)$col.names <- TRUE
formals(write.table)$sep <- "\t"
formals(write.table)$quote <- FALSE

write.table(df12, "C:/Users/iwong1/Downloads/temp.tsv")
```

