---
title: "Untitled"
output: html_document
date: "2024-11-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{sh}
ls -lh | awk9 | xargs -I {} sh -c "echo -n '{}\t'; df -h {} | grep -v Filesystem" | sed 's/[[:blank:]]+/\t/g' 
```

df0$V2 %>% str_replace_all("\\s+", "\t")

df0$V2 %>% str_replace_all("\\s+", "\t")

```{r}
df0 <- fread("C:/docs/cluster/cluster_info.tsv", header=FALSE) %>% as.data.frame()
```


```{r}
yaml <- readLines("C:/docs/temp/SQANTI3.conda_env.yml")
yaml <- yaml %>% str_remove("^[:blank:]+-[:blank:]")
temp1 <- paste0("\"", paste0(yaml, collapse = "\" \""), "\"")
cat(temp1)


```



```{r}
df0 <- data.frame(time = c(0,17,44,68,196,230,247,271,343,1400,1680),
                  count = c(12,17,26,33,74,86,91,97,120,412,309))

df0 <- data.frame(time = c(0,1745,1773,2769,4218,4332,5643,5906),
                  count = c(6,309,315,517,722,738,901,946))

x1 <- df0$time[1]
y1 <- df0$count[1]

x2 <- df0$time[nrow(df0)]
y2 <- df0$count[nrow(df0)]

m <- (y2-y1)/(x2-x1)

b = y2 - (m * x2)

t1 <- ((1074 - b)/m)*60

t2 <- as.POSIXct("2024-12-16T11:34:00Z", format="%Y-%m-%dT%H:%M:%OSZ", tz="UTC")

t2+t1
ggplot(df0, aes(x=time,y=count)) + geom_point() + ggtitle(paste0(t2+t1, " ", round(1/m, 4), " minutes/sample"))
```

```{r}
mylines <- readLines("C:/docs/aou/create_table/chr_subsets.txt")
df0 <- mylines %>% str_replace_all("[:space:]+", " ") %>% str_split(" ") %>% do.call(rbind, .) %>% as.data.frame()
df0 <- df0[grepl("subset", df0$V9), ]
df0$type <- df0$V9 %>% str_remove("subset.chr[:digit:]*.")

```

