---
title: "Untitled"
output: html_document
date: "2025-08-12"
---

```{r}
df0 <- fread("C:/docs/etc/data_kinnex_pre_release.index.csv") %>% as.data.frame()
header <- c("#!/bin/bash", "module load awscli/2.17.9", "set -euxo pipefail")


df0$dest_dir <- paste0("/net/eichler/vol28/projects/long_read_archive/nobackups/pop/", df0$sample_ID, "/raw_data/PacBio_Kinnex")
df0$script <- paste("mkdir -p ", df0$dest_dir, " ; echo ", df0$path," ; aws s3 cp ", df0$path, " ", df0$dest_dir, " --no-sign-request")
write.table(c(header, df0$script), "C:/docs/etc/hprc_kinnex_s3_paths_download.sh", sep = "\t", col.names = FALSE, row.names = FALSE, quote=FALSE) 


df0$final_path <- paste0(df0$dest_dir, "/", df0$filename)
write.table(df0$final_path, "C:/docs/etc/kinnex_intermediate_paths.txt", sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)

df0$dest_dir2 <- paste0("/net/eichler/vol28/projects/long_read_archive/nobackups/pop/", df0$sample_ID, "/raw_data/PacBio_HiFi/Kinnex")
df0$finalest_path <- paste0(df0$dest_dir2, "/", df0$filename)
df0$script2 <- paste0("mkdir -p ", df0$dest_dir2, " ; mv ", df0$final_path, " ", df0$dest_dir2, "/ ; ")
df0$script3 <- paste0("rm -rf ", df0$dest_dir)
write.table(c(header, df0$script2, df0$script3), "C:/docs/etc/hprc_kinnex_s3_paths_finalize.sh", sep = "\t", col.names = FALSE, row.names = FALSE, quote=FALSE) 

write.table(df0$finalest_path, "C:/docs/etc/data_kinnex_pre_release.index.lra_paths.txt", sep="\t", col.names = FALSE, row.names = FALSE, quote=FALSE)
```

```{r}
df0 <- fread("C:/docs/mike/Challengers Players and Lists - All Players.tsv") %>% as.data.frame()
df0 <- df0[order(df0$Elo, decreasing = TRUE), ]
df1 <- df0[grepl("Rain City Wych", df0$Team), ]

df00 <- df0
df00$List <- NULL
df00$Notes <- NULL
df00$V8 <- NULL
rownames(df00) <- seq_down(df00)

list_by_team <- lapply(u(df00$Team), function(x){
  df00[df00$Team == x, ]
})
names(list_by_team) <- u(df00$Team)

df01 <- data.frame(Team = u(df00$Team), 
                   Elo = -1)
df01$Elo <- lapply(df01$Team, function(x){
  mean(df00$Elo[df00$Team == x], na.rm = TRUE)
}) %>% unlist

df01 <- df01[order(df01$Elo, decreasing = TRUE), ]

MY_TEAM <- "Rain City Wych Pigeons - Team Emerald"






THRESHOLD <- 100

df01$CONT <- abs(df01$Elo - df01$Elo[df01$Team==MY_TEAM]) <= THRESHOLD
df01$CONT[df01$Team == MY_TEAM] <- FALSE

df02 <- list_by_team[df01$Team[df01$CONT]] %>% do.call(rbind, .)
df02$key <- paste0(df02$Faction, "  ", df02$Detachment)

temp1 <- df02$key %>% srt %>% as.data.frame()
temp2 <-  df0$Faction %>% srt %>% as.data.frame()
temp3 <-  df0$Detachment %>% srt %>% as.data.frame()
temp3$x <- temp3$x %>% as.character()

df2 <- df0[df0$Faction == "Black Templars", ]

# average Elo of opponenets, Andrew Kismarton
df3 <- rbind(df00[grepl("Brad Chester", df00$Name), ], 
             df00[grepl("Steeler French", df00$Name), ], 
             df00[grepl("Scott Spalding", df00$Name), ], 
             df00[grepl("Nell Hulslander", df00$Name), ], 
             df00[grepl("Kody Mckinnon", df00$Name), ])
```



```{r}
df000 <- data.frame(cohort = c("hprc", "ceph", "hgsvc"), files=c("C:/docs/etc/files.v2.txt", "C:/docs/etc/files.ceph.txt", "C:/docs/etc/files.hgsvc.txt"), verk=c("2.2.1", "2.2.1", "1.4.1"))

for(COHORT in seq_down(df000)){
  print(df000$cohort[COHORT])
  temp1 <- df000$files[COHORT] %>% readLines()
  
  FILLER <- ifelse(df000$cohort[COHORT] == "hprc", "", ".gz")
  
  df1 <- data.frame(sample=temp1[grepl("fa.gz$", temp1)] %>% bname %>% str_remove("_.*") %>% u)
  df1$fasta <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_chrY.fa.gz$") ,temp1)]
  }) %>% unlist
  df1$fai <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_chrY.fa", FILLER,".fai$") ,temp1)]
  }) %>% unlist
  df1$gzi <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_chrY.fa.gz.gzi$") ,temp1)]
  }) %>% unlist
  
  LRA_BASE <- "/net/eichler/vol28/projects/long_read_archive/nobackups/pop/"
  
  migrate <- function(sample, fasta, fai, gzi, curr, max){
    DEST_DIR <- paste0(LRA_BASE, sample, "/assemblies/verkko/", df000$verk[COHORT],"/")
    
    script_00 <- paste0("echo ", curr, "/", max, ": ", sample)
    script_01 <- paste0("mkdir -p ", DEST_DIR)
    script_02 <- paste0("mv ", fasta, "       ", DEST_DIR)
    script_03 <- paste0("mv ", fai, "      ", DEST_DIR)
    script_04 <- paste0("mv ", gzi, "   ", DEST_DIR)
    script_05 <- "date"
    
    c(script_00, script_01, script_02, script_03, script_04, script_05, "\n")
  }
  
  bign <- nrow(df1)
  temp2 <- lapply(seq_down(df1), function(x){
    migrate(sample=df1$sample[x], fasta=df1$fasta[x], fai=df1$fai[x], gzi=df1$gzi[x], curr=x, max=bign)}) %>% unlist
  
  temp2 <- c("#!/bin/bash", "set -euo pipefail", temp2)
  
  df10 <- data.frame(sample=df1$sample)
  TEMP_BASE <- paste0("/assemblies/verkko/", df000$verk[COHORT], "/")
  df10$fasta <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$fasta))
  df10$fai   <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$fai))
  df10$gzi   <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$gzi))
  
  # write.table(temp2, paste0("C:/docs/etc/migration.", df000$cohort[COHORT],"_y.sh"), col.names = FALSE, row.names = FALSE, quote=FALSE)
  # write.table(df10,  paste0("C:/docs/etc/manifest." , df000$cohort[COHORT],"_y.tsv"), sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)
  
  temp1_samples <- temp1[grepl("_nonY.fa.gz$", temp1)] %>% bname %>% str_remove("_.*") %>% u
  df1 <- data.frame(sample=temp1[grepl("_nonY.fa.gz$", temp1)] %>% bname %>% str_remove("_.*") %>% u)
  df1$fasta <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_nonY.fa.gz$") ,temp1)]
  }) %>% unlist
  df1$fai <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_nonY.fa", FILLER,".fai$") ,temp1)]
  }) %>% unlist
  df1$gzi <- lapply(df1$sample, function(x){
    temp1[grepl(paste0(x, "_nonY.fa.gz.gzi$") ,temp1)]
  }) %>% unlist
  
  bign <- nrow(df1)
  temp2 <- lapply(seq_down(df1), function(x){
    migrate(sample=df1$sample[x], fasta=df1$fasta[x], fai=df1$fai[x], gzi=df1$gzi[x], curr=x, max=bign)}) %>% unlist
  
  temp2 <- c("#!/bin/bash", "set -euo pipefail", temp2)
  
  df10 <- data.frame(sample=df1$sample)
  TEMP_BASE <- paste0("/assemblies/verkko/", df000$verk[COHORT], "/")
  df10$fasta <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$fasta))
  df10$fai   <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$fai))
  df10$gzi   <- paste0(LRA_BASE, df10$sample, TEMP_BASE, bname(df1$gzi))
  
  # write.table(temp2, paste0("C:/docs/etc/migration.", df000$cohort[COHORT],"_nony.sh"), col.names = FALSE, row.names = FALSE, quote=FALSE)
  # write.table(df10,  paste0("C:/docs/etc/manifest." , df000$cohort[COHORT],"_nony.tsv"), sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)
}
```

here in a box i hide the letters written 

```{r}
df1 <- fread("C:/docs/etc/manifest.ceph_nony.tsv") %>% as.data.frame()
df1$cohort <- "ceph"
df1$class <- "nony"
df2 <- fread("C:/docs/etc/manifest.ceph_y.tsv") %>% as.data.frame()
df2$cohort <- "ceph"
df2$class <- "y"
df3 <- fread("C:/docs/etc/manifest.hgsvc_nony.tsv") %>% as.data.frame()
df3$cohort <- "hgsvc"
df3$class <- "nony"
df4 <- fread("C:/docs/etc/manifest.hgsvc_y.tsv") %>% as.data.frame()
df4$cohort <- "hgsvc"
df4$class <- "y"
df5 <- fread("C:/docs/etc/manifest.hprc_nony.tsv") %>% as.data.frame()
df5$cohort <- "hprc"
df5$class <- "nony"
df6 <- fread("C:/docs/etc/manifest.hprc_y.tsv") %>% as.data.frame()
df6$cohort <- "hprc"
df6$class <- "y"

df7 <- rbind(df1, df2, df3, df4, df5, df6)
write.table(df7, "C:/docs/etc/manifest.chrynony.tsv", sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)
```



```{r}
flacs <- list.files("C:/Users/iwong1/Music/zip/", recursive = "TRUE", pattern = ".flac$")

df0 <- data.frame(path = flacs, 
                  song = flacs %>% bname %>% str_remove(".flac"), 
                  album = flacs %>% lapply(function(x){unlist(str_split(x, "/"))[1]}) %>% unlist)
temp1 <- srt(df0$album)
temp2 <- data.frame(albums)
```


find -type f  | grep flac$ | sed "s/'/\\\'/g" | xargs -I {} /bin/bash -c 'echo -e -n "{}"; ffprobe "{}" 2>&1 | grep bitrate' > ~/docs/mike/songs_bitrate.txt

```{r}
df0 <- data.frame(lines = readLines("C:/docs/mike/songs_bitrate.txt"))
df0$song <- df0$lines %>% str_extract("(?<=./).*(?=.flac)")
df0$bitrate <- df0$lines %>% str_extract("(?<=bitrate: ).*(?= kb/s)") %>% as.numeric()
df0 <- df0[order(df0$bitrate, decreasing = TRUE), ]
```

